
ARG VER=0.0.0

FROM python:3.11-slim

RUN apt-get update && apt-get install -y curl unzip

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY main.py timedlocking.py custom_logger.py pyproject.toml /app/

RUN mkdir -p /data

WORKDIR /app
RUN uv sync

CMD ["uv", "run", "/app/main.py"]
