services:
  s3:
    # image: minio/minio
    build:
      context: ../src/s3
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: localcloud
      MINIO_ROOT_PASSWORD: localcloud
      MINIO_NOTIFY_WEBHOOK_ENABLE_LAMBDA: "on"
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_LAMBDA: "http://api:4566/webhook/lambda"
      MINIO_NOTIFY_WEBHOOK_ENABLE_SQS: "on"
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_SQS: "http://api:4566/webhook/sqs"
      MINIO_NOTIFY_WEBHOOK_ENABLE_SNS: "on"
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_SNS: "http://api:4566/webhook/sns"
      AWS_ENDPOINT_URL: http://api:4566
      LOG_LEVEL: DEBUG
      NIMBUS_LISTENING_ADDR: 0.0.0.0
    volumes:
      - data-s3:/data
    networks:
      - localcloud
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  data-s3:
